// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proiect;

#nullable disable

namespace Proiect.Migrations
{
    [DbContext(typeof(CatalogContext))]
    [Migration("20250525191044_commit1")]
    partial class commit1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proiect.Models.Curs", b =>
                {
                    b.Property<int>("IdCurs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCurs"));

                    b.Property<int>("An")
                        .HasColumnType("int");

                    b.Property<int>("IdProfesor")
                        .HasColumnType("int");

                    b.Property<string>("NumeCurs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCurs");

                    b.HasIndex("IdProfesor");

                    b.ToTable("Cursuri");
                });

            modelBuilder.Entity("Proiect.Models.Nota", b =>
                {
                    b.Property<int>("IdNota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNota"));

                    b.Property<int?>("CursIdCurs")
                        .HasColumnType("int");

                    b.Property<int>("IdCurs")
                        .HasColumnType("int");

                    b.Property<int>("IdStudent")
                        .HasColumnType("int");

                    b.Property<int?>("StudentIdStudent")
                        .HasColumnType("int");

                    b.Property<float>("Valoare")
                        .HasColumnType("real");

                    b.HasKey("IdNota");

                    b.HasIndex("CursIdCurs");

                    b.HasIndex("StudentIdStudent");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("Proiect.Models.Profesor", b =>
                {
                    b.Property<int>("IdProfesor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProfesor"));

                    b.Property<string>("NumeProfesor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrenumeProfesor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProfesor");

                    b.ToTable("Profesori");
                });

            modelBuilder.Entity("Proiect.Models.Student", b =>
                {
                    b.Property<int>("IdStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStudent"));

                    b.Property<int>("Grupa")
                        .HasColumnType("int");

                    b.Property<string>("NumeStudent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrenumeStudent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdStudent");

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("Proiect.Models.Utilizator", b =>
                {
                    b.Property<int>("IdUtilizator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtilizator"));

                    b.Property<string>("NumeUtilizator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parola")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUtilizator");

                    b.ToTable("Utilizatori");
                });

            modelBuilder.Entity("Proiect.Models.Curs", b =>
                {
                    b.HasOne("Proiect.Models.Profesor", "Profesor")
                        .WithMany()
                        .HasForeignKey("IdProfesor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("Proiect.Models.Nota", b =>
                {
                    b.HasOne("Proiect.Models.Curs", "Curs")
                        .WithMany()
                        .HasForeignKey("CursIdCurs");

                    b.HasOne("Proiect.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentIdStudent");

                    b.Navigation("Curs");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
